apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookit-app
  labels:
    app: lookit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lookit-app
  template:
    
    metadata:
      labels:
        app: lookit-app
    spec:
      serviceAccountName: lookit-sa
      containers:
      - name: lookit-app-container
        # Replace with your Docker Hub image from the GitHub Action step
        image: branson404/django-app:7825568a4e703d7b8f99df087f26b0e586a7e4df
        ports:
        - containerPort: 8000
        # Resource limits prevent one pod from crashing the whole node
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
