apiVersion: v1
kind: Service
metadata:
  name: lookit-service
  namespace: django-app
  annotations:
    # This tells AWS: "Create a public-facing NLB/ALB, not an internal one"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: lookit-app
  ports:
    - protocol: TCP
      port: 80         # The port the LoadBalancer listens on
      targetPort: 8000 # The port your Django/Gunicorn app listens on
  type: LoadBalancer   # This tells EKS to provision an AWS Load Balancer
