apiVersion: v1
kind: Service
metadata:
  name: lookit-app
spec:
  selector:
    app: lookit-app
  ports:
    - protocol: TCP
      port: 80         # The port the LoadBalancer listens on
      targetPort: 8000 # The port your Django/Gunicorn app listens on
  type: LoadBalancer   # This tells EKS to provision an AWS Load Balancer
  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lookit-sa
  annotations:
    # REPLACE with your actual IAM Role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::702252493729:role/lookit-secrets-manager-role
